// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO3S7baVcsgHaXoqCOH32_YiyDLWFV1u8',
    appId: '1:312600070906:web:1746aa579fb7f410611743',
    messagingSenderId: '312600070906',
    projectId: 'ivkids',
    authDomain: 'ivkids.firebaseapp.com',
    storageBucket: 'ivkids.appspot.com',
    measurementId: 'G-7XN8ELGPGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVXII_6lccirx98EUBOmPUDokoxrCvCE',
    appId: '1:312600070906:android:db7a6fcfd1e37d35611743',
    messagingSenderId: '312600070906',
    projectId: 'ivkids',
    storageBucket: 'ivkids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDb6jLAVRbOns5lrTtCLro8FbexAWLB4',
    appId: '1:312600070906:ios:f289d42f9a34cec4611743',
    messagingSenderId: '312600070906',
    projectId: 'ivkids',
    storageBucket: 'ivkids.appspot.com',
    iosClientId: '312600070906-fu68b4un2q11btqsl2iv1fbj71hslg51.apps.googleusercontent.com',
    iosBundleId: 'com.example.ivykidsTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeDb6jLAVRbOns5lrTtCLro8FbexAWLB4',
    appId: '1:312600070906:ios:f289d42f9a34cec4611743',
    messagingSenderId: '312600070906',
    projectId: 'ivkids',
    storageBucket: 'ivkids.appspot.com',
    iosClientId: '312600070906-fu68b4un2q11btqsl2iv1fbj71hslg51.apps.googleusercontent.com',
    iosBundleId: 'com.example.ivykidsTask',
  );
}
